const languageSentences = {
    "Afrikaans": "Die hond dra 'n hoed met 'n sambreel.",
    "Albanian": "Një peshk fluturon në një biçikletë të verdhë.",
    "Asu": "Mchwa alikula kifungua kinywa na chajio.",
    "Basque": "Txakur bat pianoan jotzen ari zen esnearekin.",
    "Bemba": "Inyama ya nkhumba yalasa m'tundu.",
    "Bena": "Mfuko uliojaa nyanya za kijani.",
    "Catalan": "Un gat verd menjava gelat de xocolata.",
    "Chiga": "Ekyuma kiregi kya okugeza empale.",
    "Danish": "En grøn elefant spillede klaver i parken.",
    "Dutch": "De blauwe koe zingt een lied met accenten.",
    "English": "The purple monkey drives a lollipop car.",
    "Estonian": "Roheline kass mängib klaverit kohviga.",
    "Faroese": "Eitt súltutoy epli dansar á borðinum.",
    "Filipino": "Ang asul na baka ay kumakanta ng piyano.",
    "Finnish": "Vihreä koira soittaa kitaraa järvessä.",
    "French": "Le chien bleu joue du violon avec une girafe.",
    "Friulian": "Un mîr a cjante un puem sot dal çiel.",
    "Galician": "O gato verde baila unha muñeira.",
    "German": "Der rote Vogel trinkt eine Tasse Tee.",
    "Gusii": "Nkobe igoro yagura mbura igana.",
    "Hungarian": "A lila nyúl eszik egy sajtos muffint.",
    "Icelandic": "Græna höfrungurinn les bók um sólina.",
    "Indonesian": "Kucing hijau bermain gitar di pantai.",
    "Irish": "An cat glas ag seinm ceoil ar an bpléaráca.",
    "Italian": "Un cavallo verde dipinge un quadro blu.",
    "Kabuverdianu": "Um cao azul ta kanta na praia.",
    "Kalenjin": "Chepkurkur chepyoset kyeben kyoset ak koros.",
    "Kinyarwanda": "Imbwa itukura irya inyama z'umweru.",
    "Latvian": "Zaļais suns spēlē vijoli ar kaķi.",
    "Lithuanian": "Žalias šuo groja smuiku su mėlynu katinu.",
    "Low German": "De gröne Hund speelt mit een Katt op'n Klavier.",
    "Lower Sorbian": "Zeleni psě gryjo na harmoniju z myšom.",
    "Luo": "Okadhi mari kothe aringe kendo kode.",
    "Luxembourgish": "De gréngen Hond spillt Musek mat enger Maus.",
    "Luyia": "Ekhokho eravoolera embusi nayo omukhasi.",
    "Machame": "Kiboko kibulaya jibu na kinywa kilalu.",
    "Makhuwa-Meetto": "Namulele wanjambuli akhala na ntanya.",
    "Makonde": "Chizi chikulya miunda cha ng'ona.",
    "Malagasy": "Alika maintso mandihy amin'ny vorona manga.",
    "Malay": "Gajah biru bermain biola di pantai.",
    "Manx": "Yn doo glonney t'ad ginnaghey gee smullaght.",
    "Morisyen": "Enn lisien ver zwe lamizik ar enn zariko.",
    "North Ndebele": "Inja eluhlaza edla izithelo zamabhola.",
    "Norwegian Bokmål": "Jeg så en katt med to glass øl.",
    "Norwegian Nynorsk": "Eg såg ein katt med to glas øl.",
    "Nyankole": "Enkoko yanjura eijumwa n'ekyamugyira.",
    "Oromo": "Harree garbuu mana kuussa fi foon nyaata.",
    "Polish": "Zielony pies gra na fortepianie z kotem.",
    "Portuguese": "O gato verde toca guitarra com um peixe.",
    "Romanian": "Un elefant verde cântă la pian.",
    "Romansh": "In chaun verd suna la ghitarra.",
    "Rombo": "Ng'ombe nyekundu anacheza na jogoo.",
    "Rundi": "Inka y'ibitoke irya imihwi n'ingurube.",
    "Rwa": "Mbuzi jekundu anakula machungwa.",
    "Samburu": "Nkima naji kata kata lchoo.",
    "Sango": "Mburu ya walaba tiso na ndako.",
    "Sangu": "N'kuku yebule kwa nyama no nyama.",
    "Scottish Gaelic": "Tha cù uaine a' cluich le leabhar bàn.",
    "Sena": "Kambwe kamuwa njoka na sitoni.",
    "Shambala": "Mbuzi nyekundu inaenda na ndege.",
    "Shona": "Imbwa iri kuuya nemota yegoridhe.",
    "Slovak": "Zelený pes hrá na husliach s myšou.",
    "Slovenian": "Zelena mačka igra violino s psom.",
    "Soga": "Akasa kwenyama emba embuzi.",
    "Somali": "Eyga cagaaran baa cunto barafuunka.",
    "Spanish": "El elefante azul toca la guitarra.",
    "Swahili": "Paka kijani anacheza dansi na simba.",
    "Swedish": "Den gröna hunden spelar piano i skogen.",
    "Swiss German": "Dr grön Hund spielt Gitarre mit em Muus.",
    "Taita": "Ghãmbo jithe na nyamu za thambo.",
    "Teso": "Ekito ye itele na njira ekiro.",
    "Turkish": "Yeşil kedi bir turşu yiyor.",
    "Turkmen": "Ýaşyl it ýorunçak bilen oýnaýar.",
    "Upper Sorbian": "Zelene psy hrajónu harmoniku z myšu.",
    "Vunjo": "Ng'ombe mwekundu anakula na ndege.",
    "Welsh": "Mae ci gwyrdd yn canu gyda mochyn.",
    "Western Frisian": "In griene kat boartsje mei in fisk.",
    "Zulu": "Inja eluhlaza edla isinkwa esibomvu."
};

document.addEventListener('DOMContentLoaded', () => {
    const buttons = document.querySelectorAll('.language-tag');
    const sentenceBox = document.querySelector('.gen-sentence');

    buttons.forEach(button => {
        button.addEventListener('click', () => {
            const language = button.getAttribute('data-language');
            const sentence = languageSentences[language];
            sentenceBox.textContent = sentence;
        });
    });
});
